[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"
